name: circom
run-name: ${{ github.actor }} is building a circom circuit
on: [push]
jobs:
  circom-build-circuit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install circom
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
          git clone https://github.com/iden3/circom.git
          cd circom
          cargo build --release
          cargo install --path circom
      - name: run circom
        run: circom --help
      - name: install snarkjs
        run: npm install -g snarkjs@latest
      - name: install zeto
        run: |
          git clone https://github.com/hyperledger-labs/zeto.git
          cd zkp/circuits
          npm install
          cd ..
          circom circuits/anon_enc_nullifier.circom --output ./js/lib --sym --wasm
          circom circuits/anon_enc.circom --output ./js/lib --sym --wasm

