name: Circuit Unit Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - 'doc-site/**'
      - '.github/workflows/docs.yaml'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'doc-site/**'
      - '.github/workflows/docs.yaml'
  workflow_dispatch:

jobs:
  circuit-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install circom
        uses: supplypike/setup-bin@v4
        with:
          uri: https://github.com/iden3/circom/releases/download/v2.2.2/circom-linux-amd64
          name: circom
          version: 2.2.2

      - name: Checkout circuits
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install circuit dependencies
        working-directory: zkp/circuits
        run: |
          npm install

      - name: Run circuit unit tests
        working-directory: zkp/js
        run: |
          npm install
          npm t
