name: Docs Site

on:
  push:
    branches:
      - main
    paths:
      - "doc-site/docs/**"
      - ".github/workflows/docs.yaml"
  pull_request:
    paths:
      - "doc-site/docs/**"
      - ".github/workflows/docs.yaml"
  release:
    types: [released]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LATEST_TAG: ""
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Docs Deploy
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"

      - name: Get the latest tag
        run: |
          git fetch --tags
          latest_tag=$(git tag -l | sort -V | grep -v "rc" | tail -n 1)
          echo "latest tag: $latest_tag"
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Install docs dependencies
        working-directory: doc-site
        run: pip install -r requirements.txt

      - name: Update doc site for release
        if: github.event.action == 'released' && github.ref_name != env.LATEST_TAG
        working-directory: doc-site
        run: mike deploy ${{ github.event.release.tag_name }} --push

      - name: Update doc site for latest release
        if: github.event.action == 'released' && github.ref_name == env.LATEST_TAG
        working-directory: doc-site
        run: |
          mike deploy ${{ github.event.release.tag_name }} latest -u --push
          mike set-default --push latest

      - name: Update doc site for `main` branch
        if: ${{ github.event_name == 'push' }}
        working-directory: doc-site
        run: mike deploy head --push

      - name: Test building the doc site but do not deploy it
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: doc-site
        run: mkdocs build
