name: files
run-name: ${{ github.actor }} is copying files to container
on:
  push:
    paths:
      - '.github/workflows/files.yaml'    
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: copy files
        run: |
          pwd
          ls -a
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Containerized Build
        uses: ./.github/actions/



